# Mock customer data for prototype
MOCK_CUSTOMERS = [
    {
        "id": 1,
        "name": "Acme Corp",
        "mrr": 5000,
        "usage_score": 0.1,
        "support_tickets": 8,
        "last_login_days": 45,
        "contract_date": "2023-01-15",
    },
    {
        "id": 2,
        "name": "Tech Solutions Ltd",
        "mrr": 3000,
        "usage_score": 0.4,
        "support_tickets": 2,
        "last_login_days": 16,
        "contract_date": "2023-03-01",
    },
    {
        "id": 3,
        "name": "Innovation Inc",
        "mrr": 8000,
        "usage_score": 0.8,
        "support_tickets": 1,
        "last_login_days": 2,
        "contract_date": "2022-12-01",
    },
    {
        "id": 4,
        "name": "StartupCo",
        "mrr": 2000,
        "usage_score": 0.9,
        "support_tickets": 0,
        "last_login_days": 1,
        "contract_date": "2023-06-15",
    },
    {
        "id": 5,
        "name": "Global Enterprises",
        "mrr": 15000,
        "usage_score": 0.2,
        "support_tickets": 12,
        "last_login_days": 30,
        "contract_date": "2022-08-01",
    },
    {
        "id": 6,
        "name": "Digital Dynamics",
        "mrr": 4500,
        "usage_score": 0.7,
        "support_tickets": 1,
        "last_login_days": 3,
        "contract_date": "2023-02-20",
    },
    {
        "id": 7,
        "name": "Future Systems",
        "mrr": 6500,
        "usage_score": 0.6,
        "support_tickets": 3,
        "last_login_days": 5,
        "contract_date": "2023-04-10",
    },
    {
        "id": 8,
        "name": "CloudFirst LLC",
        "mrr": 3500,
        "usage_score": 0.3,
        "support_tickets": 6,
        "last_login_days": 20,
        "contract_date": "2023-01-30",
    },
    {
        "id": 9,
        "name": "DataDriven Co",
        "mrr": 7200,
        "usage_score": 0.85,
        "support_tickets": 0,
        "last_login_days": 1,
        "contract_date": "2022-11-15",
    },
    {
        "id": 10,
        "name": "ScaleUp Technologies",
        "mrr": 2800,
        "usage_score": 0.5,
        "support_tickets": 4,
        "last_login_days": 8,
        "contract_date": "2023-05-01",
    },
    {
        "id": 11,
        "name": "Enterprise Solutions",
        "mrr": 12000,
        "usage_score": 0.75,
        "support_tickets": 2,
        "last_login_days": 4,
        "contract_date": "2022-09-01",
    },
    {
        "id": 12,
        "name": "NextGen Industries",
        "mrr": 4000,
        "usage_score": 0.4,
        "support_tickets": 5,
        "last_login_days": 12,
        "contract_date": "2023-02-01",
    },
    {
        "id": 13,
        "name": "Rapid Growth Inc",
        "mrr": 5500,
        "usage_score": 0.9,
        "support_tickets": 1,
        "last_login_days": 2,
        "contract_date": "2023-07-01",
    },
    {
        "id": 14,
        "name": "Legacy Corp",
        "mrr": 9000,
        "usage_score": 0.25,
        "support_tickets": 9,
        "last_login_days": 35,
        "contract_date": "2022-06-01",
    },
    {
        "id": 15,
        "name": "Modern Workflows",
        "mrr": 3200,
        "usage_score": 0.65,
        "support_tickets": 2,
        "last_login_days": 6,
        "contract_date": "2023-03-15",
    },
]

# Predefined action templates for different scenarios
ACTION_TEMPLATES = {
    "churn_risk": [
        "Schedule urgent call with decision maker",
        "Send personalized retention offer",
        "Escalate to account manager",
        "Provide executive business review",
    ],
    "engagement_risk": [
        "Send check-in email",
        "Share new feature updates",
        "Schedule product training session",
        "Invite to user community",
    ],
    "usage_decline": [
        "Analyze feature adoption gaps",
        "Provide usage optimization consultation",
        "Send best practices guide",
        "Schedule success review call",
    ],
    "support_overload": [
        "Schedule technical review session",
        "Escalate to technical team",
        "Provide additional training resources",
        "Review implementation approach",
    ],
}
